import type {
  ConcreteThemeId,
  CornerStyle,
  PierreThemeName,
  ResolvedAppearance,
  ThemeDefinition,
  ThemeId,
  ThemeTokens,
} from "./types"

const DEFAULT_TERMINAL_FONT_FAMILY =
  'SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace'

type ThemeSeed = {
  id: ConcreteThemeId
  label: string
  appearance: ResolvedAppearance
  background: string
  surface: string
  surfaceElevated: string
  foreground: string
  mutedForeground: string
  border: string
  input?: string
  sidebarBorder?: string
  controlBorder?: string
  ring: string
  primary: string
  primaryForeground: string
  secondary?: string
  secondaryForeground?: string
  accent?: string
  accentForeground?: string
  destructive: string
  success: string
  warning: string
  info: string
  renamed: string
  ignored: string
  cta?: string
  ctaForeground?: string
  toggleOn?: string
  skillAccent?: string
  skillSurface?: string
  chart: [string, string, string, string, string]
  chatFileAccent?: string
  chatPlanAccent?: string
  chatApprovalEmphasis?: string
}

function mix(color: string, weight: number, background: string): string {
  return `color-mix(in oklab, ${color} ${weight}%, ${background})`
}

function withAlpha(color: string, alpha: number): string {
  return `color-mix(in oklab, ${color} ${alpha}%, transparent)`
}

function createMonacoTheme(seed: ThemeSeed): ThemeDefinition["monaco"] {
  const isDark = seed.appearance === "dark"
  const selection = isDark ? withAlpha(seed.primary, 28) : withAlpha(seed.primary, 20)
  const lineHighlight = isDark ? withAlpha(seed.foreground, 6) : withAlpha(seed.foreground, 4)

  return {
    id: `vfactor-${seed.id}`,
    base: isDark ? "vs-dark" : "vs",
    inherit: true,
    rules: [
      { token: "", foreground: seed.foreground.replace("#", "") },
      { token: "comment", foreground: seed.mutedForeground.replace("#", ""), fontStyle: "italic" },
      { token: "keyword", foreground: seed.primary.replace("#", "") },
      { token: "string", foreground: seed.success.replace("#", "") },
      { token: "number", foreground: seed.warning.replace("#", "") },
      { token: "delimiter", foreground: seed.foreground.replace("#", "") },
      { token: "type.identifier", foreground: seed.info.replace("#", "") },
      { token: "function", foreground: seed.renamed.replace("#", "") },
    ],
    colors: {
      "editor.background": seed.surface,
      "editor.foreground": seed.foreground,
      "editorLineNumber.foreground": withAlpha(seed.mutedForeground, 80),
      "editorLineNumber.activeForeground": seed.foreground,
      "editorCursor.foreground": seed.primary,
      "editor.selectionBackground": selection,
      "editor.lineHighlightBackground": lineHighlight,
      "editor.inactiveSelectionBackground": withAlpha(seed.primary, 14),
      "editorIndentGuide.background1": withAlpha(seed.foreground, 8),
      "editorIndentGuide.activeBackground1": withAlpha(seed.primary, 32),
      "editorWhitespace.foreground": withAlpha(seed.mutedForeground, 42),
      "editorWidget.background": seed.surfaceElevated,
      "editorWidget.border": seed.border,
      "editorGutter.background": seed.surface,
      "diffEditor.insertedTextBackground": withAlpha(seed.success, 18),
      "diffEditor.removedTextBackground": withAlpha(seed.destructive, 16),
      "diffEditor.insertedLineBackground": withAlpha(seed.success, 10),
      "diffEditor.removedLineBackground": withAlpha(seed.destructive, 10),
    },
  }
}

function createTheme(seed: ThemeSeed): ThemeDefinition {
  const isDark = seed.appearance === "dark"
  const border = mix(seed.foreground, isDark ? 14 : 15, seed.border)
  const controlBorder = seed.controlBorder ?? mix(seed.foreground, isDark ? 18 : 15, seed.background)
  const input = seed.input ?? mix(seed.foreground, isDark ? 12 : 11, seed.background)
  const sidebarBorder = seed.sidebarBorder ?? mix(seed.foreground, isDark ? 11 : 8, seed.background)
  const secondary = seed.secondary ?? mix(seed.foreground, isDark ? 18 : 10, seed.background)
  const accent = seed.accent ?? mix(seed.primary, isDark ? 34 : 26, seed.surfaceElevated)
  const muted = mix(seed.foreground, isDark ? 14 : 10, seed.surface)
  const cta = seed.cta ?? seed.primary
  const skillAccent = seed.skillAccent ?? seed.primary
  const chatPlanAccent = seed.chatPlanAccent ?? seed.primary
  const chatApprovalEmphasis = seed.chatApprovalEmphasis ?? seed.warning
  const sidebar = mix(seed.foreground, isDark ? 5 : 2, seed.background)
  const sidebarAccent = mix(seed.foreground, isDark ? 13 : 7, seed.background)
  const mainContent = seed.background
  const terminal = mix(seed.foreground, isDark ? 4 : 1.8, seed.background)
  const pierreTheme: PierreThemeName = isDark ? "pierre-dark" : "pierre-light"
  const contentSubtle = withAlpha(seed.foreground, isDark ? 76 : 70)

  const tokens: ThemeTokens = {
    background: seed.background,
    foreground: seed.foreground,
    "content-strong": seed.foreground,
    content: seed.foreground,
    "content-subtle": contentSubtle,
    "content-muted": seed.mutedForeground,
    "icon-strong": seed.foreground,
    icon: seed.foreground,
    "icon-subtle": contentSubtle,
    "icon-muted": seed.mutedForeground,
    card: seed.surface,
    "card-foreground": seed.foreground,
    popover: seed.surfaceElevated,
    "popover-foreground": seed.foreground,
    primary: seed.primary,
    "primary-foreground": seed.primaryForeground,
    secondary,
    "secondary-foreground": seed.secondaryForeground ?? seed.foreground,
    muted,
    "muted-foreground": seed.mutedForeground,
    accent,
    "accent-foreground": seed.accentForeground ?? seed.foreground,
    destructive: seed.destructive,
    "destructive-foreground": isDark ? "#1a1114" : "#fff7f9",
    "destructive-surface": mix(seed.destructive, isDark ? 18 : 13, seed.background),
    "destructive-surface-foreground": isDark
      ? mix(seed.destructive, 86, "#ffffff")
      : mix(seed.destructive, 72, "#0f0a0b"),
    "destructive-border": mix(seed.destructive, isDark ? 34 : 22, seed.background),
    border,
    "control-border": controlBorder,
    input,
    ring: seed.ring,
    cta,
    "cta-foreground": seed.ctaForeground ?? seed.primaryForeground,
    "toggle-on": seed.toggleOn ?? seed.primary,
    "skill-accent": skillAccent,
    "skill-icon": skillAccent,
    "skill-surface": seed.skillSurface ?? mix(skillAccent, isDark ? 20 : 14, seed.background),
    "chart-1": seed.chart[0],
    "chart-2": seed.chart[1],
    "chart-3": seed.chart[2],
    "chart-4": seed.chart[3],
    "chart-5": seed.chart[4],
    sidebar,
    "sidebar-foreground": seed.foreground,
    "sidebar-primary": seed.primary,
    "sidebar-primary-foreground": seed.primaryForeground,
    "sidebar-accent": sidebarAccent,
    "sidebar-accent-foreground": seed.foreground,
    "sidebar-glass": withAlpha(sidebar, isDark ? 84 : 70),
    "sidebar-glass-strong": withAlpha(sidebar, isDark ? 92 : 82),
    "sidebar-item-hover": mix(seed.foreground, isDark ? 16 : 10, seed.background),
    "sidebar-item-active": mix(seed.primary, isDark ? 34 : 24, seed.background),
    "sidebar-border": sidebarBorder,
    "sidebar-ring": seed.ring,
    "main-content": mainContent,
    "main-content-foreground": seed.foreground,
    "terminal-font-family": DEFAULT_TERMINAL_FONT_FAMILY,
    terminal,
    "terminal-foreground": seed.foreground,
    "terminal-cursor": seed.primary,
    "terminal-selection": withAlpha(seed.primary, isDark ? 24 : 20),
    "terminal-border": sidebarBorder,
    "chat-file-accent": seed.chatFileAccent ?? seed.info,
    "chat-plan-surface": mix(chatPlanAccent, isDark ? 16 : 10, seed.background),
    "chat-plan-border": mix(chatPlanAccent, isDark ? 34 : 24, seed.background),
    "chat-plan-accent": chatPlanAccent,
    "chat-plan-accent-foreground": isDark ? "#0f1118" : "#ffffff",
    "chat-approval-surface": mix(chatApprovalEmphasis, isDark ? 12 : 8, seed.background),
    "chat-approval-surface-strong": mix(chatApprovalEmphasis, isDark ? 18 : 12, seed.background),
    "chat-approval-border": mix(chatApprovalEmphasis, isDark ? 30 : 20, seed.background),
    "chat-approval-badge": mix(chatApprovalEmphasis, isDark ? 24 : 14, seed.background),
    "chat-approval-emphasis": chatApprovalEmphasis,
    "chat-approval-emphasis-foreground": isDark ? "#17120b" : "#fffaf2",
    "scrollbar-thumb": withAlpha(seed.mutedForeground, isDark ? 88 : 72),
    "message-user-bubble": accent,
    "message-user-bubble-foreground": seed.accentForeground ?? seed.foreground,
    success: seed.success,
    "success-foreground": isDark ? "#07170d" : "#f7fff9",
    "success-surface": mix(seed.success, isDark ? 20 : 14, seed.background),
    "success-surface-foreground": isDark
      ? mix(seed.success, 84, "#ffffff")
      : mix(seed.success, 70, "#0a100c"),
    "success-border": mix(seed.success, isDark ? 36 : 24, seed.background),
    warning: seed.warning,
    "warning-foreground": isDark ? "#191107" : "#fffaf2",
    "warning-surface": mix(seed.warning, isDark ? 18 : 12, seed.background),
    "warning-surface-foreground": isDark
      ? mix(seed.warning, 82, "#ffffff")
      : mix(seed.warning, 70, "#110d07"),
    "warning-border": mix(seed.warning, isDark ? 34 : 22, seed.background),
    info: seed.info,
    "info-foreground": isDark ? "#09131b" : "#f5fbff",
    "info-surface": mix(seed.info, isDark ? 18 : 12, seed.background),
    "info-surface-foreground": isDark
      ? mix(seed.info, 82, "#ffffff")
      : mix(seed.info, 70, "#071117"),
    "info-border": mix(seed.info, isDark ? 34 : 22, seed.background),
    "vcs-added": seed.success,
    "vcs-added-surface": mix(seed.success, isDark ? 18 : 12, seed.background),
    "vcs-modified": seed.warning,
    "vcs-modified-surface": mix(seed.warning, isDark ? 16 : 10, seed.background),
    "vcs-deleted": seed.destructive,
    "vcs-deleted-surface": mix(seed.destructive, isDark ? 16 : 10, seed.background),
    "vcs-renamed": seed.renamed,
    "vcs-renamed-surface": mix(seed.renamed, isDark ? 18 : 12, seed.background),
    "vcs-ignored": seed.ignored,
    "vcs-ignored-surface": mix(seed.ignored, isDark ? 18 : 12, seed.background),
    "vcs-ahead": seed.success,
    "vcs-behind": seed.info,
    "vcs-diverged": seed.destructive,
    "vcs-merged": seed.renamed,
    "vcs-pr-open": seed.success,
    "vcs-pr-closed": seed.ignored,
  }

  return {
    id: seed.id,
    label: seed.label,
    appearance: seed.appearance,
    tokens,
    monaco: createMonacoTheme(seed),
    adapters: {
      terminal: {
        usesCssVariables: true,
        backgroundVariable: "--terminal",
        foregroundVariable: "--terminal-foreground",
        cursorVariable: "--terminal-cursor",
      },
      diff: {
        pierreTheme,
      },
    },
  }
}

export const THEME_REGISTRY: Record<ConcreteThemeId, ThemeDefinition> = {
  "vfactor-light": createTheme({
    id: "vfactor-light",
    label: "vFactor Light",
    appearance: "light",
    background: "#f5f5f5",
    surface: "#ffffff",
    surfaceElevated: "#ffffff",
    foreground: "#000000",
    mutedForeground: "#606060",
    border: "#d9d9d9",
    ring: "#333333",
    primary: "#5f5f5f",
    primaryForeground: "#ffffff",
    secondary: "#dedede",
    secondaryForeground: "#000000",
    accent: "#e8e8e8",
    accentForeground: "#000000",
    cta: "#111111",
    ctaForeground: "#ffffff",
    toggleOn: "#111111",
    destructive: "#b54747",
    success: "#287a52",
    warning: "#a66a20",
    info: "#326f9f",
    renamed: "#6f5f9f",
    ignored: "#888888",
    skillAccent: "#111111",
    skillSurface: "#f0f0f0",
    chart: ["#111111", "#6f5f9f", "#287a52", "#a66a20", "#888888"],
    chatFileAccent: "#326f9f",
    chatPlanAccent: "#111111",
    chatApprovalEmphasis: "#a66a20",
  }),
  "vfactor-dark": createTheme({
    id: "vfactor-dark",
    label: "vFactor Dark",
    appearance: "dark",
    background: "#050505",
    surface: "#0a0a0a",
    surfaceElevated: "#111111",
    foreground: "#ffffff",
    mutedForeground: "#8a8a8a",
    border: "#1a1a1a",
    ring: "#e5e5e5",
    primary: "#b7a6ff",
    primaryForeground: "#050505",
    secondary: "#1f1f1f",
    secondaryForeground: "#e5e5e5",
    accent: "#2a2a2a",
    accentForeground: "#ffffff",
    cta: "#ffffff",
    ctaForeground: "#050505",
    toggleOn: "#ffffff",
    destructive: "#ff6b6b",
    success: "#57d68d",
    warning: "#f0b45b",
    info: "#7bb7e8",
    renamed: "#b7a6ff",
    ignored: "#666666",
    skillAccent: "#ffffff",
    skillSurface: "#111111",
    chart: ["#ffffff", "#b7a6ff", "#57d68d", "#f0b45b", "#666666"],
    chatFileAccent: "#7bb7e8",
    chatPlanAccent: "#ffffff",
    chatApprovalEmphasis: "#f0b45b",
  }),
  tokyonight: createTheme({
    id: "tokyonight",
    label: "Tokyonight",
    appearance: "dark",
    background: "#1a1b26",
    surface: "#1f2335",
    surfaceElevated: "#24283b",
    foreground: "#c0caf5",
    mutedForeground: "#9aa5ce",
    border: "#3b4261",
    input: "#24283b",
    ring: "#7aa2f7",
    primary: "#7aa2f7",
    primaryForeground: "#1a1b26",
    destructive: "#f7768e",
    success: "#9ece6a",
    warning: "#e0af68",
    info: "#7dcfff",
    renamed: "#bb9af7",
    ignored: "#565f89",
    skillAccent: "#bb9af7",
    skillSurface: "#322b4c",
    chart: ["#7aa2f7", "#bb9af7", "#7dcfff", "#e0af68", "#f7768e"],
    chatFileAccent: "#7dcfff",
    chatPlanAccent: "#7aa2f7",
    chatApprovalEmphasis: "#e0af68",
  }),
  everforest: createTheme({
    id: "everforest",
    label: "Everforest",
    appearance: "dark",
    background: "#2b3339",
    surface: "#323c41",
    surfaceElevated: "#3a464c",
    foreground: "#d3c6aa",
    mutedForeground: "#9da9a0",
    border: "#4f5b58",
    input: "#3a464c",
    ring: "#a7c080",
    primary: "#a7c080",
    primaryForeground: "#1f2529",
    destructive: "#e67e80",
    success: "#a7c080",
    warning: "#dbbc7f",
    info: "#7fbbb3",
    renamed: "#d699b6",
    ignored: "#859289",
    skillAccent: "#d699b6",
    skillSurface: "#423947",
    chart: ["#a7c080", "#7fbbb3", "#d699b6", "#dbbc7f", "#e67e80"],
    chatFileAccent: "#7fbbb3",
    chatPlanAccent: "#a7c080",
    chatApprovalEmphasis: "#dbbc7f",
  }),
  ayu: createTheme({
    id: "ayu",
    label: "Ayu",
    appearance: "dark",
    background: "#0f1419",
    surface: "#131721",
    surfaceElevated: "#1f2430",
    foreground: "#e6e1cf",
    mutedForeground: "#b3b1ad",
    border: "#273747",
    input: "#1f2430",
    ring: "#ffb454",
    primary: "#ffb454",
    primaryForeground: "#0f1419",
    destructive: "#f07178",
    success: "#b8cc52",
    warning: "#ffb454",
    info: "#59c2ff",
    renamed: "#d2a6ff",
    ignored: "#626a73",
    skillAccent: "#d2a6ff",
    skillSurface: "#302947",
    chart: ["#ffb454", "#59c2ff", "#b8cc52", "#d2a6ff", "#f07178"],
    chatFileAccent: "#59c2ff",
    chatPlanAccent: "#ffb454",
    chatApprovalEmphasis: "#ffb454",
  }),
  catppuccin: createTheme({
    id: "catppuccin",
    label: "Catppuccin",
    appearance: "dark",
    background: "#11111b",
    surface: "#181825",
    surfaceElevated: "#1e1e2e",
    foreground: "#cdd6f4",
    mutedForeground: "#a6adc8",
    border: "#313244",
    input: "#1e1e2e",
    ring: "#89b4fa",
    primary: "#89b4fa",
    primaryForeground: "#11111b",
    destructive: "#f38ba8",
    success: "#a6e3a1",
    warning: "#f9e2af",
    info: "#74c7ec",
    renamed: "#cba6f7",
    ignored: "#7f849c",
    skillAccent: "#cba6f7",
    skillSurface: "#302546",
    chart: ["#89b4fa", "#cba6f7", "#94e2d5", "#fab387", "#f38ba8"],
    chatFileAccent: "#89dceb",
    chatPlanAccent: "#89b4fa",
    chatApprovalEmphasis: "#f9e2af",
  }),
  "catppuccin-latte": createTheme({
    id: "catppuccin-latte",
    label: "Catppuccin Latte",
    appearance: "light",
    background: "#eff1f5",
    surface: "#e6e9ef",
    surfaceElevated: "#ffffff",
    foreground: "#4c4f69",
    mutedForeground: "#6c6f85",
    border: "#ccd0da",
    input: "#dce0e8",
    ring: "#7287fd",
    primary: "#7287fd",
    primaryForeground: "#eff1f5",
    destructive: "#d20f39",
    success: "#40a02b",
    warning: "#df8e1d",
    info: "#1e66f5",
    renamed: "#8839ef",
    ignored: "#8c8fa1",
    skillAccent: "#8839ef",
    skillSurface: "#efe3ff",
    chart: ["#7287fd", "#ea76cb", "#179299", "#df8e1d", "#8839ef"],
    chatFileAccent: "#1e66f5",
    chatPlanAccent: "#7287fd",
    chatApprovalEmphasis: "#df8e1d",
  }),
  "catppuccin-macchiato": createTheme({
    id: "catppuccin-macchiato",
    label: "Catppuccin Macchiato",
    appearance: "dark",
    background: "#24273a",
    surface: "#1e2030",
    surfaceElevated: "#363a4f",
    foreground: "#cad3f5",
    mutedForeground: "#a5adcb",
    border: "#494d64",
    input: "#363a4f",
    ring: "#8aadf4",
    primary: "#8aadf4",
    primaryForeground: "#181926",
    destructive: "#ed8796",
    success: "#a6da95",
    warning: "#eed49f",
    info: "#7dc4e4",
    renamed: "#c6a0f6",
    ignored: "#8087a2",
    skillAccent: "#c6a0f6",
    skillSurface: "#392f4f",
    chart: ["#8aadf4", "#c6a0f6", "#7dc4e4", "#eed49f", "#ed8796"],
    chatFileAccent: "#7dc4e4",
    chatPlanAccent: "#8aadf4",
    chatApprovalEmphasis: "#eed49f",
  }),
  "catppuccin-mocha": createTheme({
    id: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    appearance: "dark",
    background: "#1e1e2e",
    surface: "#181825",
    surfaceElevated: "#313244",
    foreground: "#cdd6f4",
    mutedForeground: "#a6adc8",
    border: "#45475a",
    input: "#313244",
    ring: "#89b4fa",
    primary: "#89b4fa",
    primaryForeground: "#11111b",
    destructive: "#f38ba8",
    success: "#a6e3a1",
    warning: "#f9e2af",
    info: "#74c7ec",
    renamed: "#cba6f7",
    ignored: "#7f849c",
    skillAccent: "#cba6f7",
    skillSurface: "#332a4a",
    chart: ["#89b4fa", "#f5c2e7", "#94e2d5", "#fab387", "#cba6f7"],
    chatFileAccent: "#89dceb",
    chatPlanAccent: "#89b4fa",
    chatApprovalEmphasis: "#f9e2af",
  }),
  "rose-pine-dawn": createTheme({
    id: "rose-pine-dawn",
    label: "Rosé Pine Dawn",
    appearance: "light",
    background: "#faf4ed",
    surface: "#fffaf3",
    surfaceElevated: "#fffefd",
    foreground: "#575279",
    mutedForeground: "#797593",
    border: "#dfdad9",
    input: "#efe1d6",
    ring: "#907aa9",
    primary: "#907aa9",
    primaryForeground: "#faf4ed",
    destructive: "#b4637a",
    success: "#56949f",
    warning: "#ea9d34",
    info: "#286983",
    renamed: "#907aa9",
    ignored: "#9893a5",
    skillAccent: "#907aa9",
    skillSurface: "#efe6f7",
    chart: ["#56949f", "#907aa9", "#286983", "#ea9d34", "#d7827e"],
    chatFileAccent: "#286983",
    chatPlanAccent: "#907aa9",
    chatApprovalEmphasis: "#ea9d34",
  }),
  "rose-pine-main": createTheme({
    id: "rose-pine-main",
    label: "Rosé Pine Main",
    appearance: "dark",
    background: "#191724",
    surface: "#1f1d2e",
    surfaceElevated: "#26233a",
    foreground: "#e0def4",
    mutedForeground: "#908caa",
    border: "#403d52",
    input: "#26233a",
    ring: "#c4a7e7",
    primary: "#c4a7e7",
    primaryForeground: "#191724",
    destructive: "#eb6f92",
    success: "#9ccfd8",
    warning: "#f6c177",
    info: "#31748f",
    renamed: "#c4a7e7",
    ignored: "#6e6a86",
    skillAccent: "#c4a7e7",
    skillSurface: "#312b45",
    chart: ["#9ccfd8", "#c4a7e7", "#31748f", "#f6c177", "#ebbcba"],
    chatFileAccent: "#9ccfd8",
    chatPlanAccent: "#c4a7e7",
    chatApprovalEmphasis: "#f6c177",
  }),
  gruvbox: createTheme({
    id: "gruvbox",
    label: "Gruvbox",
    appearance: "dark",
    background: "#282828",
    surface: "#1d2021",
    surfaceElevated: "#3c3836",
    foreground: "#ebdbb2",
    mutedForeground: "#bdae93",
    border: "#665c54",
    input: "#3c3836",
    ring: "#b8bb26",
    primary: "#b8bb26",
    primaryForeground: "#282828",
    destructive: "#fb4934",
    success: "#b8bb26",
    warning: "#fabd2f",
    info: "#83a598",
    renamed: "#d3869b",
    ignored: "#928374",
    skillAccent: "#d3869b",
    skillSurface: "#3b2f3a",
    chart: ["#b8bb26", "#83a598", "#d3869b", "#fabd2f", "#fb4934"],
    chatFileAccent: "#83a598",
    chatPlanAccent: "#b8bb26",
    chatApprovalEmphasis: "#fabd2f",
  }),
  kanagawa: createTheme({
    id: "kanagawa",
    label: "Kanagawa",
    appearance: "dark",
    background: "#1f1f28",
    surface: "#16161d",
    surfaceElevated: "#2a2a37",
    foreground: "#dcd7ba",
    mutedForeground: "#9cabca",
    border: "#54546d",
    input: "#2a2a37",
    ring: "#7e9cd8",
    primary: "#7e9cd8",
    primaryForeground: "#16161d",
    destructive: "#c34043",
    success: "#76946a",
    warning: "#c0a36e",
    info: "#7aa89f",
    renamed: "#957fb8",
    ignored: "#727169",
    skillAccent: "#957fb8",
    skillSurface: "#332b43",
    chart: ["#7e9cd8", "#957fb8", "#7aa89f", "#c0a36e", "#c34043"],
    chatFileAccent: "#7aa89f",
    chatPlanAccent: "#7e9cd8",
    chatApprovalEmphasis: "#c0a36e",
  }),
  henna: createTheme({
    id: "henna",
    label: "Henna Color Theme",
    appearance: "light",
    background: "#f8f8f0",
    surface: "#ece8dc",
    surfaceElevated: "#fffdf4",
    foreground: "#3b4048",
    mutedForeground: "#606f73",
    border: "#d7d2c4",
    input: "#ece8dc",
    ring: "#1abc9c",
    primary: "#1abc9c",
    primaryForeground: "#10151a",
    destructive: "#e74c3c",
    success: "#53df83",
    warning: "#fd7c56",
    info: "#56b5c2",
    renamed: "#b85c8a",
    ignored: "#6b717d",
    skillAccent: "#b85c8a",
    skillSurface: "#f5e4eb",
    chart: ["#1abc9c", "#56b5c2", "#53df83", "#fd7c56", "#e74c3c"],
    chatFileAccent: "#56b5c2",
    chatPlanAccent: "#1abc9c",
    chatApprovalEmphasis: "#fd7c56",
  }),
  "github-light": createTheme({
    id: "github-light",
    label: "GitHub Light",
    appearance: "light",
    background: "#ffffff",
    surface: "#f6f8fa",
    surfaceElevated: "#ffffff",
    foreground: "#24292f",
    mutedForeground: "#57606a",
    border: "#d0d7de",
    input: "#eaeef2",
    ring: "#0969da",
    primary: "#0969da",
    primaryForeground: "#ffffff",
    destructive: "#cf222e",
    success: "#1a7f37",
    warning: "#9a6700",
    info: "#0969da",
    renamed: "#8250df",
    ignored: "#6e7781",
    skillAccent: "#8250df",
    skillSurface: "#f1e5ff",
    chart: ["#0969da", "#8250df", "#1a7f37", "#9a6700", "#cf222e"],
    chatFileAccent: "#0969da",
    chatPlanAccent: "#0969da",
    chatApprovalEmphasis: "#9a6700",
  }),
  "tokyo-night-storm": createTheme({
    id: "tokyo-night-storm",
    label: "Tokyo Night Storm",
    appearance: "dark",
    background: "#1f2335",
    surface: "#24283b",
    surfaceElevated: "#292e42",
    foreground: "#c0caf5",
    mutedForeground: "#9aa5ce",
    border: "#3b4261",
    input: "#292e42",
    ring: "#7aa2f7",
    primary: "#7aa2f7",
    primaryForeground: "#1f2335",
    destructive: "#f7768e",
    success: "#9ece6a",
    warning: "#e0af68",
    info: "#7dcfff",
    renamed: "#bb9af7",
    ignored: "#565f89",
    skillAccent: "#bb9af7",
    skillSurface: "#322b4c",
    chart: ["#7aa2f7", "#bb9af7", "#7dcfff", "#e0af68", "#f7768e"],
    chatFileAccent: "#7dcfff",
    chatPlanAccent: "#7aa2f7",
    chatApprovalEmphasis: "#e0af68",
  }),
  nord: createTheme({
    id: "nord",
    label: "Nord",
    appearance: "dark",
    background: "#2e3440",
    surface: "#3b4252",
    surfaceElevated: "#434c5e",
    foreground: "#eceff4",
    mutedForeground: "#d8dee9",
    border: "#4c566a",
    input: "#434c5e",
    ring: "#88c0d0",
    primary: "#88c0d0",
    primaryForeground: "#2e3440",
    destructive: "#bf616a",
    success: "#a3be8c",
    warning: "#ebcb8b",
    info: "#81a1c1",
    renamed: "#b48ead",
    ignored: "#616e88",
    skillAccent: "#b48ead",
    skillSurface: "#41384d",
    chart: ["#88c0d0", "#b48ead", "#81a1c1", "#ebcb8b", "#bf616a"],
    chatFileAccent: "#81a1c1",
    chatPlanAccent: "#88c0d0",
    chatApprovalEmphasis: "#ebcb8b",
  }),
  matrix: createTheme({
    id: "matrix",
    label: "Matrix",
    appearance: "dark",
    background: "#050805",
    surface: "#071107",
    surfaceElevated: "#0c1d0c",
    foreground: "#b8ffb8",
    mutedForeground: "#5fae66",
    border: "#174d1f",
    input: "#0c1d0c",
    ring: "#00ff41",
    primary: "#00ff41",
    primaryForeground: "#001905",
    destructive: "#ff4f6d",
    success: "#00ff41",
    warning: "#b6ff63",
    info: "#5cff8d",
    renamed: "#81ffb2",
    ignored: "#3e7346",
    skillAccent: "#81ffb2",
    skillSurface: "#0d2315",
    chart: ["#00ff41", "#5cff8d", "#81ffb2", "#b6ff63", "#ff4f6d"],
    chatFileAccent: "#5cff8d",
    chatPlanAccent: "#00ff41",
    chatApprovalEmphasis: "#b6ff63",
  }),
  "night-owl": createTheme({
    id: "night-owl",
    label: "Night Owl",
    appearance: "dark",
    background: "#011627",
    surface: "#071d2f",
    surfaceElevated: "#0b253a",
    foreground: "#d6deeb",
    mutedForeground: "#7fdbca",
    border: "#18344f",
    input: "#0b253a",
    ring: "#82aaff",
    primary: "#82aaff",
    primaryForeground: "#011627",
    destructive: "#ef5350",
    success: "#addb67",
    warning: "#ffcb8b",
    info: "#21c7a8",
    renamed: "#c792ea",
    ignored: "#637777",
    skillAccent: "#c792ea",
    skillSurface: "#201d3a",
    chart: ["#82aaff", "#c792ea", "#21c7a8", "#ffcb8b", "#ef5350"],
    chatFileAccent: "#21c7a8",
    chatPlanAccent: "#82aaff",
    chatApprovalEmphasis: "#ffcb8b",
  }),
  dracula: createTheme({
    id: "dracula",
    label: "Dracula",
    appearance: "dark",
    background: "#282a36",
    surface: "#2f3342",
    surfaceElevated: "#343746",
    foreground: "#f8f8f2",
    mutedForeground: "#9aa3cf",
    border: "#44475a",
    input: "#343746",
    ring: "#8be9fd",
    primary: "#bd93f9",
    primaryForeground: "#282a36",
    destructive: "#ff5555",
    success: "#50fa7b",
    warning: "#f1fa8c",
    info: "#8be9fd",
    renamed: "#ff79c6",
    ignored: "#6272a4",
    skillAccent: "#ff79c6",
    skillSurface: "#422c49",
    chart: ["#bd93f9", "#ff79c6", "#8be9fd", "#f1fa8c", "#50fa7b"],
    chatFileAccent: "#8be9fd",
    chatPlanAccent: "#bd93f9",
    chatApprovalEmphasis: "#f1fa8c",
  }),
  "ayu-light": createTheme({
    id: "ayu-light",
    label: "Ayu Light",
    appearance: "light",
    background: "#f8f9fa",
    surface: "#fcfcfc",
    surfaceElevated: "#ffffff",
    foreground: "#5c6166",
    mutedForeground: "#828e9f",
    border: "#ebeef0",
    input: "#e4e8eb",
    ring: "#f29718",
    primary: "#f29718",
    primaryForeground: "#fffaf2",
    destructive: "#f07171",
    success: "#86b300",
    warning: "#fa8d3e",
    info: "#399ee6",
    renamed: "#a37acc",
    ignored: "#a0a6ac",
    skillAccent: "#a37acc",
    skillSurface: "#f1ebfb",
    chart: ["#399ee6", "#a37acc", "#4cbf99", "#fa8d3e", "#f07171"],
    chatFileAccent: "#399ee6",
    chatPlanAccent: "#f29718",
    chatApprovalEmphasis: "#fa8d3e",
  }),
  "ayu-mirage": createTheme({
    id: "ayu-mirage",
    label: "Ayu Mirage",
    appearance: "dark",
    background: "#1f2430",
    surface: "#242936",
    surfaceElevated: "#282e3b",
    foreground: "#cccac2",
    mutedForeground: "#707a8c",
    border: "#303744",
    input: "#282e3b",
    ring: "#ffcc66",
    primary: "#ffcc66",
    primaryForeground: "#1f2430",
    destructive: "#ff6666",
    success: "#87d96c",
    warning: "#ffcd66",
    info: "#73d0ff",
    renamed: "#dfbfff",
    ignored: "#6e7c8f",
    skillAccent: "#dfbfff",
    skillSurface: "#312b46",
    chart: ["#73d0ff", "#dfbfff", "#95e6cb", "#ffa659", "#f28779"],
    chatFileAccent: "#73d0ff",
    chatPlanAccent: "#ffcc66",
    chatApprovalEmphasis: "#ffa659",
  }),
  "kanagawa-lotus": createTheme({
    id: "kanagawa-lotus",
    label: "Kanagawa Lotus",
    appearance: "light",
    background: "#f2ecbc",
    surface: "#e7dba0",
    surfaceElevated: "#d5cea3",
    foreground: "#545464",
    mutedForeground: "#716e61",
    border: "#dcd7ba",
    input: "#e5dca4",
    ring: "#4d699b",
    primary: "#4d699b",
    primaryForeground: "#f9f7ec",
    destructive: "#c84053",
    success: "#6f894e",
    warning: "#e98a00",
    info: "#5a7785",
    renamed: "#624c83",
    ignored: "#8a8980",
    skillAccent: "#624c83",
    skillSurface: "#ece7f3",
    chart: ["#4d699b", "#624c83", "#597b75", "#e98a00", "#c84053"],
    chatFileAccent: "#4d699b",
    chatPlanAccent: "#624c83",
    chatApprovalEmphasis: "#e98a00",
  }),
  "kanagawa-dragon": createTheme({
    id: "kanagawa-dragon",
    label: "Kanagawa Dragon",
    appearance: "dark",
    background: "#181616",
    surface: "#282727",
    surfaceElevated: "#393836",
    foreground: "#c5c9c5",
    mutedForeground: "#a6a69c",
    border: "#625e5a",
    input: "#393836",
    ring: "#8ba4b0",
    primary: "#8ba4b0",
    primaryForeground: "#181616",
    destructive: "#c4746e",
    success: "#87a987",
    warning: "#c4b28a",
    info: "#658594",
    renamed: "#a292a3",
    ignored: "#9e9b93",
    skillAccent: "#a292a3",
    skillSurface: "#352f35",
    chart: ["#8ba4b0", "#a292a3", "#8ea4a2", "#c4b28a", "#c4746e"],
    chatFileAccent: "#8ba4b0",
    chatPlanAccent: "#a292a3",
    chatApprovalEmphasis: "#c4b28a",
  }),
  noctis: createTheme({
    id: "noctis",
    label: "Noctis",
    appearance: "dark",
    background: "#052529",
    surface: "#07313a",
    surfaceElevated: "#0b3b46",
    foreground: "#c5d9d7",
    mutedForeground: "#7aa0a5",
    border: "#164e55",
    input: "#0b3b46",
    ring: "#49d6e9",
    primary: "#49e9a6",
    primaryForeground: "#052529",
    destructive: "#df769b",
    success: "#49e9a6",
    warning: "#e4b781",
    info: "#49ace9",
    renamed: "#8f80ff",
    ignored: "#5b858b",
    skillAccent: "#df769b",
    skillSurface: "#30213a",
    chart: ["#49e9a6", "#49d6e9", "#49ace9", "#e4b781", "#df769b"],
    chatFileAccent: "#49d6e9",
    chatPlanAccent: "#49e9a6",
    chatApprovalEmphasis: "#e4b781",
  }),
  rainglow: createTheme({
    id: "rainglow",
    label: "Rainglow",
    appearance: "dark",
    background: "#171926",
    surface: "#202437",
    surfaceElevated: "#2a3048",
    foreground: "#f4f7ff",
    mutedForeground: "#a2accf",
    border: "#3b4261",
    input: "#2a3048",
    ring: "#36c5f0",
    primary: "#36c5f0",
    primaryForeground: "#10131f",
    destructive: "#ff5d8f",
    success: "#8ee88e",
    warning: "#ffd166",
    info: "#5cc8ff",
    renamed: "#c792ea",
    ignored: "#7c86ad",
    skillAccent: "#ff8bd1",
    skillSurface: "#3a2449",
    chart: ["#36c5f0", "#ff8bd1", "#8ee88e", "#ffd166", "#c792ea"],
    chatFileAccent: "#5cc8ff",
    chatPlanAccent: "#36c5f0",
    chatApprovalEmphasis: "#ffd166",
  }),
  cyberpunk: createTheme({
    id: "cyberpunk",
    label: "Cyberpunk",
    appearance: "dark",
    background: "#0d0221",
    surface: "#16052f",
    surfaceElevated: "#24104a",
    foreground: "#e8fbff",
    mutedForeground: "#9b8bc8",
    border: "#3b1f62",
    input: "#241047",
    ring: "#00f0ff",
    primary: "#00ff9f",
    primaryForeground: "#071313",
    destructive: "#ff006e",
    success: "#00ff9f",
    warning: "#fcee09",
    info: "#00f0ff",
    renamed: "#bd00ff",
    ignored: "#76689f",
    skillAccent: "#ff006e",
    skillSurface: "#3a0a3f",
    chart: ["#00ff9f", "#00f0ff", "#ff006e", "#fcee09", "#bd00ff"],
    chatFileAccent: "#00f0ff",
    chatPlanAccent: "#00ff9f",
    chatApprovalEmphasis: "#fcee09",
  }),
  "gruvbox-material": createTheme({
    id: "gruvbox-material",
    label: "Gruvbox Material",
    appearance: "dark",
    background: "#1d2021",
    surface: "#282828",
    surfaceElevated: "#32302f",
    foreground: "#d4be98",
    mutedForeground: "#a89984",
    border: "#504945",
    input: "#32302f",
    ring: "#a9b665",
    primary: "#a9b665",
    primaryForeground: "#1d2021",
    destructive: "#ea6962",
    success: "#a9b665",
    warning: "#d8a657",
    info: "#7daea3",
    renamed: "#d3869b",
    ignored: "#928374",
    skillAccent: "#d3869b",
    skillSurface: "#3a2e38",
    chart: ["#a9b665", "#7daea3", "#d3869b", "#d8a657", "#ea6962"],
    chatFileAccent: "#7daea3",
    chatPlanAccent: "#a9b665",
    chatApprovalEmphasis: "#d8a657",
  }),
  moonlight: createTheme({
    id: "moonlight",
    label: "Moonlight",
    appearance: "dark",
    background: "#222436",
    surface: "#2f334d",
    surfaceElevated: "#383d5c",
    foreground: "#c8d3f5",
    mutedForeground: "#828bb8",
    border: "#4a5278",
    input: "#2f334d",
    ring: "#82aaff",
    primary: "#82aaff",
    primaryForeground: "#151725",
    destructive: "#ff757f",
    success: "#c3e88d",
    warning: "#ffc777",
    info: "#65bcff",
    renamed: "#c099ff",
    ignored: "#6b739c",
    skillAccent: "#c099ff",
    skillSurface: "#352d55",
    chart: ["#82aaff", "#c099ff", "#65bcff", "#ffc777", "#c3e88d"],
    chatFileAccent: "#65bcff",
    chatPlanAccent: "#82aaff",
    chatApprovalEmphasis: "#ffc777",
  }),
  "aurora-x": createTheme({
    id: "aurora-x",
    label: "Aurora X",
    appearance: "dark",
    background: "#07090f",
    surface: "#0f1724",
    surfaceElevated: "#172033",
    foreground: "#d6deff",
    mutedForeground: "#8b98c6",
    border: "#263250",
    input: "#172033",
    ring: "#00e5ff",
    primary: "#00e5ff",
    primaryForeground: "#061018",
    destructive: "#ff3864",
    success: "#36f9a5",
    warning: "#ffe66d",
    info: "#82aaff",
    renamed: "#c792ea",
    ignored: "#687197",
    skillAccent: "#ff79c6",
    skillSurface: "#321f43",
    chart: ["#00e5ff", "#36f9a5", "#ff79c6", "#ffe66d", "#c792ea"],
    chatFileAccent: "#82aaff",
    chatPlanAccent: "#00e5ff",
    chatApprovalEmphasis: "#ffe66d",
  }),
  "field-lights": createTheme({
    id: "field-lights",
    label: "Field Lights",
    appearance: "dark",
    background: "#1f2430",
    surface: "#242936",
    surfaceElevated: "#2b3140",
    foreground: "#d7d9db",
    mutedForeground: "#8b95a8",
    border: "#303744",
    input: "#2b3140",
    ring: "#ffcc66",
    primary: "#ffcc66",
    primaryForeground: "#1f2430",
    destructive: "#f28779",
    success: "#bae67e",
    warning: "#ffa759",
    info: "#73d0ff",
    renamed: "#d4bfff",
    ignored: "#6e7c8f",
    skillAccent: "#d4bfff",
    skillSurface: "#332d45",
    chart: ["#ffcc66", "#73d0ff", "#bae67e", "#ffa759", "#d4bfff"],
    chatFileAccent: "#73d0ff",
    chatPlanAccent: "#ffcc66",
    chatApprovalEmphasis: "#ffa759",
  }),
  "just-black": createTheme({
    id: "just-black",
    label: "Just Black",
    appearance: "dark",
    background: "#000000",
    surface: "#0d0d0d",
    surfaceElevated: "#181818",
    foreground: "#f2f2f2",
    mutedForeground: "#999999",
    border: "#2d2d2d",
    input: "#181818",
    sidebarBorder: "#242424",
    controlBorder: "#343434",
    ring: "#d7d7d7",
    primary: "#f2f2f2",
    primaryForeground: "#050505",
    destructive: "#ff5c5c",
    success: "#7ddf8a",
    warning: "#e8d27a",
    info: "#9ad7ff",
    renamed: "#c7a8ff",
    ignored: "#6f6f6f",
    skillAccent: "#c7a8ff",
    skillSurface: "#17121f",
    chart: ["#f2f2f2", "#9ad7ff", "#7ddf8a", "#e8d27a", "#c7a8ff"],
    chatFileAccent: "#9ad7ff",
    chatPlanAccent: "#f2f2f2",
    chatApprovalEmphasis: "#e8d27a",
  }),
}

export const CONCRETE_THEMES = Object.values(THEME_REGISTRY)

export const THEME_OPTIONS: Array<{ id: ThemeId; label: string }> = [
  { id: "system", label: "System" },
  ...CONCRETE_THEMES.map((theme) => ({ id: theme.id, label: theme.label })),
]

export const DEFAULT_THEME_ID: ThemeId = "system"
export const DEFAULT_TEXT_SIZE_PX = 13
export const MIN_TEXT_SIZE_PX = 12
export const MAX_TEXT_SIZE_PX = 16
export const TEXT_SIZE_STEP_PX = 1
export const DEFAULT_CORNER_STYLE: CornerStyle = "soft"
export const CORNER_STYLE_OPTIONS: Array<{ id: CornerStyle; label: string; description: string }> = [
  {
    id: "square",
    label: "Square",
    description: "Flat app chrome with hard editor-style corners.",
  },
  {
    id: "soft",
    label: "Soft",
    description: "Balanced corners for everyday app surfaces.",
  },
  {
    id: "rounded",
    label: "Rounded",
    description: "Larger, friendlier corners across panels and chat.",
  },
]

const CORNER_STYLE_RADIUS: Record<CornerStyle, string> = {
  square: "0rem",
  soft: "0.625rem",
  rounded: "1rem",
}

export function isThemeId(value: string | null | undefined): value is ThemeId {
  return value === "system" || value in THEME_REGISTRY
}

export function normalizeThemeId(value: string | null | undefined): ThemeId {
  return isThemeId(value) ? value : DEFAULT_THEME_ID
}

export function isCornerStyle(value: string | null | undefined): value is CornerStyle {
  return value === "square" || value === "soft" || value === "rounded"
}

export function getCornerStyleRadius(style: CornerStyle): string {
  return CORNER_STYLE_RADIUS[style]
}

export function clampTextSizePx(value: number | null | undefined): number {
  if (!Number.isFinite(value)) {
    return DEFAULT_TEXT_SIZE_PX
  }

  return Math.min(MAX_TEXT_SIZE_PX, Math.max(MIN_TEXT_SIZE_PX, Math.round(value)))
}

export function resolveThemeIdForAppearance(appearance: ResolvedAppearance): ConcreteThemeId {
  return appearance === "dark" ? "vfactor-dark" : "vfactor-light"
}

export function getThemeDefinition(themeId: ConcreteThemeId): ThemeDefinition {
  return THEME_REGISTRY[themeId]
}
