export const IPC_CHANNELS = {
  appGetVersion: "app:getVersion",
  appCheckForUpdates: "app:checkForUpdates",
  appInstallUpdate: "app:installUpdate",
  dialogOpenProjectFolder: "dialog:openProjectFolder",
  fsReadTextFile: "fs:readTextFile",
  fsWriteTextFile: "fs:writeTextFile",
  fsExists: "fs:exists",
  fsReadDir: "fs:readDir",
  fsMkdir: "fs:mkdir",
  fsHomeDir: "fs:homeDir",
  fsCopyPathsIntoDirectory: "fs:copyPathsIntoDirectory",
  storeGet: "store:get",
  storeSet: "store:set",
  storeDelete: "store:delete",
  storeSave: "store:save",
  watcherStart: "watcher:start",
  watcherStop: "watcher:stop",
  codexEnsureServer: "codex:ensureServer",
  codexSend: "codex:send",
  terminalCreateSession: "terminal:createSession",
  terminalWrite: "terminal:write",
  terminalResize: "terminal:resize",
  terminalCloseSession: "terminal:closeSession",
  gitGetBranches: "git:getBranches",
  gitCheckoutBranch: "git:checkoutBranch",
  gitCreateAndCheckoutBranch: "git:createAndCheckoutBranch",
  skillsList: "skills:list",
} as const

export const EVENT_CHANNELS = {
  appUpdate: "app-update:event",
  projectFs: "project-fs:event",
  codexMessage: "codex-rpc:message",
  codexStatus: "codex-rpc:status",
  terminalData: "terminal:data",
  terminalExit: "terminal:exit",
} as const
