export const IPC_CHANNELS = {
  appGetVersion: "app:getVersion",
  appGetUpdateState: "app:getUpdateState",
  appCheckForUpdates: "app:checkForUpdates",
  appInstallUpdate: "app:installUpdate",
  appDismissUpdate: "app:dismissUpdate",
  dialogOpenProjectFolder: "dialog:openProjectFolder",
  fsReadTextFile: "fs:readTextFile",
  fsReadFileAsDataUrl: "fs:readFileAsDataUrl",
  fsWriteTextFile: "fs:writeTextFile",
  fsWriteDataUrlFile: "fs:writeDataUrlFile",
  fsExists: "fs:exists",
  fsReadDir: "fs:readDir",
  fsMkdir: "fs:mkdir",
  fsRemovePath: "fs:removePath",
  fsHomeDir: "fs:homeDir",
  fsCopyPathsIntoDirectory: "fs:copyPathsIntoDirectory",
  storeGet: "store:get",
  storeSet: "store:set",
  storeDelete: "store:delete",
  storeSave: "store:save",
  watcherStart: "watcher:start",
  watcherStop: "watcher:stop",
  codexEnsureServer: "codex:ensureServer",
  codexSend: "codex:send",
  shellOpenExternal: "shell:openExternal",
  terminalCreateSession: "terminal:createSession",
  terminalWrite: "terminal:write",
  terminalResize: "terminal:resize",
  terminalCloseSession: "terminal:closeSession",
  gitGetBranches: "git:getBranches",
  gitGetChanges: "git:getChanges",
  gitGetPullRequestChecks: "git:getPullRequestChecks",
  gitListWorktrees: "git:listWorktrees",
  gitCreateWorktree: "git:createWorktree",
  gitRemoveWorktree: "git:removeWorktree",
  gitRenameWorktree: "git:renameWorktree",
  gitGetFileDiff: "git:getFileDiff",
  gitCheckoutBranch: "git:checkoutBranch",
  gitCreateAndCheckoutBranch: "git:createAndCheckoutBranch",
  gitPull: "git:pull",
  gitMergePullRequest: "git:mergePullRequest",
  gitEnsureInfoExcludeEntries: "git:ensureInfoExcludeEntries",
  gitRunStackedAction: "git:runStackedAction",
  skillsList: "skills:list",
} as const

export const EVENT_CHANNELS = {
  appUpdateState: "app-update:state",
  projectFs: "project-fs:event",
  codexMessage: "codex-rpc:message",
  codexStatus: "codex-rpc:status",
  terminalData: "terminal:data",
  terminalExit: "terminal:exit",
  gitActionProgress: "git-action:progress",
} as const
