export const MIN_MAIN_CONTENT_WIDTH = 405
export const WINDOW_CONTROLS_GUTTER_WIDTH = 80
export const DESKTOP_LEFT_TOGGLE_OFFSET = WINDOW_CONTROLS_GUTTER_WIDTH + 12
export const COLLAPSED_LEFT_TOGGLE_WIDTH = 28
export const LEFT_SIDEBAR_COLLAPSED_WIDTH =
  DESKTOP_LEFT_TOGGLE_OFFSET + COLLAPSED_LEFT_TOGGLE_WIDTH
export const LEFT_SIDEBAR_WIDTH_CSS_VAR = "--nucleus-left-sidebar-width"
export const RIGHT_SIDEBAR_WIDTH_CSS_VAR = "--nucleus-right-sidebar-width"
export const SIDEBAR_OPEN_DURATION_S = 0.56
export const SIDEBAR_CLOSE_DURATION_S = 0.4
export const SIDEBAR_COLLAPSE_SETTLE_MS = SIDEBAR_CLOSE_DURATION_S * 1000
